# Generated by Django 3.0 on 2019-12-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=7)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades1', to='trades.Redditor')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades2', to='trades.Redditor')),
            ],
        ),
    ]
