# Generated by Django 3.0 on 2019-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='comment_url',
            field=models.CharField(default='https://reddit.com/', max_length=200),
            preserve_default=False,
        ),
    ]
