# Generated by Django 3.0 on 2019-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_comment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='comment_datetime',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
    ]
