# Generated by Django 3.0 on 2019-12-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade_comment_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='comment_datetime',
            new_name='confirmation_datetime',
        ),
    ]
